# 使用 GitHub Actions 实现自动每日更新
name: update_live

on:
  schedule:
    - cron: "0 * * * *"
    # - cron: 0 */6 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: npm install
        run: |
          npm install
      - name: "运行脚本"
        run: |
          node auto.js

      - name: Setup Git
        shell: bash
        run: |
          git config user.name "bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config --global push.followTags true

      - name: Commit and push changes
        run: |
          git add live
          git commit -m "Auto update live $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
